// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kplxvppxqgitywxlsrjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwbHh2cHB4cWdpdHl3eGxzcmpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzODE3MjcsImV4cCI6MjA1OTk1NzcyN30.jIgtBnFsP4NdzK36Cp2Psh7rJ6IPDLhWfzoe-4TnqNM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);